package com.newput.bean;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbggenerated Wed Sep 30 17:28:31 IST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.EmployeeName
     *
     * @mbggenerated Wed Sep 30 17:28:31 IST 2015
     */
    private String employeename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.Address
     *
     * @mbggenerated Wed Sep 30 17:28:31 IST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.Email
     *
     * @mbggenerated Wed Sep 30 17:28:31 IST 2015
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbggenerated Wed Sep 30 17:28:31 IST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbggenerated Wed Sep 30 17:28:31 IST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.EmployeeName
     *
     * @return the value of employee.EmployeeName
     *
     * @mbggenerated Wed Sep 30 17:28:31 IST 2015
     */
    public String getEmployeename() {
        return employeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.EmployeeName
     *
     * @param employeename the value for employee.EmployeeName
     *
     * @mbggenerated Wed Sep 30 17:28:31 IST 2015
     */
    public void setEmployeename(String employeename) {
        this.employeename = employeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.Address
     *
     * @return the value of employee.Address
     *
     * @mbggenerated Wed Sep 30 17:28:31 IST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.Address
     *
     * @param address the value for employee.Address
     *
     * @mbggenerated Wed Sep 30 17:28:31 IST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.Email
     *
     * @return the value of employee.Email
     *
     * @mbggenerated Wed Sep 30 17:28:31 IST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.Email
     *
     * @param email the value for employee.Email
     *
     * @mbggenerated Wed Sep 30 17:28:31 IST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }
}