package com.app.newput.controller.group;

import java.io.Serializable;

public class Testing implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testing.Id
     *
     * @mbggenerated Thu Sep 24 09:18:32 IST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testing.name
     *
     * @mbggenerated Thu Sep 24 09:18:32 IST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testing.address
     *
     * @mbggenerated Thu Sep 24 09:18:32 IST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testing.email
     *
     * @mbggenerated Thu Sep 24 09:18:32 IST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table testing
     *
     * @mbggenerated Thu Sep 24 09:18:32 IST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testing.Id
     *
     * @return the value of testing.Id
     *
     * @mbggenerated Thu Sep 24 09:18:32 IST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testing.Id
     *
     * @param id the value for testing.Id
     *
     * @mbggenerated Thu Sep 24 09:18:32 IST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testing.name
     *
     * @return the value of testing.name
     *
     * @mbggenerated Thu Sep 24 09:18:32 IST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testing.name
     *
     * @param name the value for testing.name
     *
     * @mbggenerated Thu Sep 24 09:18:32 IST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testing.address
     *
     * @return the value of testing.address
     *
     * @mbggenerated Thu Sep 24 09:18:32 IST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testing.address
     *
     * @param address the value for testing.address
     *
     * @mbggenerated Thu Sep 24 09:18:32 IST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testing.email
     *
     * @return the value of testing.email
     *
     * @mbggenerated Thu Sep 24 09:18:32 IST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testing.email
     *
     * @param email the value for testing.email
     *
     * @mbggenerated Thu Sep 24 09:18:32 IST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }
}